Add protocol messages for progress notifications
eclipse-glsp/glsp-website-source pull request #91
Opened 2023-07-13 17:07 UTC by planger

https://github.com/eclipse-glsp/glsp/issues/1019

2023-07-13 22:22 UTC, tortmayr requested changes

2023-07-13 22:22 UTC, tortmayr commented on content/documentation/protocol/content.md
> +This action extends the corresponding Sprotty action to include a timeout.
```suggestion
```

2023-07-13 22:22 UTC, tortmayr commented on content/documentation/protocol/content.md
> +If a timeout is given the respective status should disappear after the timeout is reached.
```suggestion
```

2023-07-14 07:21 UTC, planger commented on content/documentation/protocol/content.md
> +This action extends the corresponding Sprotty action to include a timeout.
The `ServerStatusAction` still has a `timeout` property. See https://github.com/eclipse-glsp/glsp-client/blob/master/packages/protocol/src/action-protocol/client-notification.ts#L40

Imho there was no reason to remove it, given that we are handling the status in glsp-client directly showing an overlay. Also it makes sense to have these two types of messages imho: 
- a single status message that can be shown at a given time to raise the awareness of something for a certain period
- messages, which are persistent and multiple ones can be collected over time

2023-07-14 07:22 UTC, planger commented on content/documentation/protocol/content.md
> +If a timeout is given the respective status should disappear after the timeout is reached.
See comment above.

2023-07-14 08:49 UTC, tortmayr approved these changes

2023-07-14 09:04 UTC, merged